#!/usr/bin/env bash
#
# deploy.sh — provision + deploy redditprofile (Next.js 16 + PostgreSQL/Prisma)
# Target:    Ubuntu VPS, app on port 3000, served at https://redditprofile.com
#
# Idempotent: every step checks for existing state and SKIPS work already done,
# so it is safe to re-run for updates. Run as root (or with sudo).
#
#   sudo bash deploy.sh
#
# First run will prompt-free generate a JWT secret and a Postgres password and
# write them into /opt/redditprofile/.env. Fill in the optional API keys after.
# ---------------------------------------------------------------------------

set -euo pipefail

# ----------------------------- configuration -------------------------------
APP_NAME="redditprofile"
APP_DIR="/opt/${APP_NAME}"
REPO_URL="https://github.com/Asad-noob69/redditprofile.git"
BRANCH="main"
PORT="3000"
DOMAIN="redditprofile.com"
NODE_MAJOR="22"

DB_NAME="redditprofile"
DB_USER="redditprofile"

# Set ENABLE_SSL=0 to skip certbot (e.g. before DNS points at this box)
ENABLE_SSL="${ENABLE_SSL:-1}"
# Email used for Let's Encrypt registration
CERTBOT_EMAIL="${CERTBOT_EMAIL:-admin@${DOMAIN}}"

# ----------------------------- helpers -------------------------------------
log()  { echo -e "\n\033[1;34m==>\033[0m \033[1m$*\033[0m"; }
skip() { echo -e "    \033[0;32m[skip]\033[0m $*"; }
have() { command -v "$1" >/dev/null 2>&1; }

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run as root:  sudo bash deploy.sh" >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

# ----------------------------- 1. base packages ----------------------------
log "Base packages (git, curl, build tools)"
if ! have git || ! have curl; then
  apt-get update -y
  apt-get install -y git curl ca-certificates gnupg ufw openssl
else
  skip "git/curl already installed"
fi

# ----------------------------- 2. Node.js ----------------------------------
log "Node.js ${NODE_MAJOR}.x"
if have node && [ "$(node -v | sed 's/v\([0-9]*\).*/\1/')" -ge "$NODE_MAJOR" ]; then
  skip "node $(node -v) already installed"
else
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y nodejs
fi

# ----------------------------- 3. PM2 --------------------------------------
log "PM2 process manager"
if have pm2; then
  skip "pm2 already installed"
else
  npm install -g pm2
  pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true
fi

# ----------------------------- 4. PostgreSQL -------------------------------
log "PostgreSQL server"
if have psql && systemctl is-active --quiet postgresql; then
  skip "postgresql already installed and running"
else
  apt-get install -y postgresql postgresql-contrib
  systemctl enable --now postgresql
fi

log "Database role + database"
# Create role if missing
if sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
  skip "role '${DB_USER}' already exists"
  DB_PASS=""   # leave existing password as-is
else
  DB_PASS="$(openssl rand -hex 24)"
  sudo -u postgres psql -c "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}';"
fi
# Create database if missing
if sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  skip "database '${DB_NAME}' already exists"
else
  sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"
fi
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};" >/dev/null

# ----------------------------- 5. source code ------------------------------
log "Application source at ${APP_DIR}"
if [ -d "${APP_DIR}/.git" ]; then
  skip "repo present — pulling latest"
  git -C "${APP_DIR}" fetch --depth 1 origin "${BRANCH}"
  git -C "${APP_DIR}" reset --hard "origin/${BRANCH}"
else
  git clone --branch "${BRANCH}" "${REPO_URL}" "${APP_DIR}"
fi
cd "${APP_DIR}"

# ----------------------------- 6. environment file -------------------------
log "Environment file (.env)"
if [ -f "${APP_DIR}/.env" ]; then
  skip ".env already exists — leaving it untouched"
else
  JWT_SECRET="$(openssl rand -hex 32)"
  # If we created a fresh DB role above, use that password; otherwise the admin
  # must paste the existing password into DATABASE_URL manually.
  PASS_FOR_URL="${DB_PASS:-CHANGE_ME}"
  cat > "${APP_DIR}/.env" <<EOF
# --- generated by deploy.sh on first run ---
DATABASE_URL="postgresql://${DB_USER}:${PASS_FOR_URL}@localhost:5432/${DB_NAME}?schema=public"
JWT_SECRET="${JWT_SECRET}"

NODE_ENV=production
APP_URL=https://${DOMAIN}

# Admin dashboard (REQUIRED) — set real values:
ADMIN_USERNAME=admin
ADMIN_PASSWORD=change-me-now

# --- optional integrations (fill in as needed) ---
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
NEXT_PUBLIC_GOOGLE_CLIENT_ID=
BRAVE_SEARCH_API_KEY=
NEXT_PUBLIC_TURNSTILE_SITE_KEY=
TURNSTILE_SECRET_KEY=
POLAR_ACCESS_TOKEN=
POLAR_PRODUCT_ID=
POLAR_WEBHOOK_SECRET=
RESEND_API_KEY=
SUPPORT_EMAIL_FROM="RedditProfile Support <support@${DOMAIN}>"
SUPPORT_REPLY_TO=
ADMIN_NOTIFICATION_EMAIL=
EOF
  chmod 600 "${APP_DIR}/.env"
  echo "    Wrote ${APP_DIR}/.env — review ADMIN_PASSWORD and optional keys."
  if [ -z "${DB_PASS:-}" ]; then
    echo "    NOTE: an existing DB role was reused; set its password in DATABASE_URL."
  fi
fi

# ----------------------------- 7. build ------------------------------------
log "Install dependencies"
npm ci || npm install

log "Prisma generate + migrate"
npx prisma generate
npx prisma migrate deploy

log "Seed admin user (first deploy only)"
if [ -f "${APP_DIR}/.seeded" ]; then
  skip "already seeded"
else
  npx tsx prisma/seed.ts && touch "${APP_DIR}/.seeded"
fi

log "Build Next.js production bundle"
npm run build

# ----------------------------- 8. run via PM2 ------------------------------
log "Start / reload app with PM2 on port ${PORT}"
if pm2 describe "${APP_NAME}" >/dev/null 2>&1; then
  pm2 reload "${APP_NAME}" --update-env
else
  pm2 start npm --name "${APP_NAME}" -- start -- -p "${PORT}"
fi
pm2 save

# ----------------------------- 9. Nginx reverse proxy ----------------------
log "Nginx reverse proxy for ${DOMAIN}"
if ! have nginx; then
  apt-get install -y nginx
fi

NGINX_SITE="/etc/nginx/sites-available/${APP_NAME}"
if [ -f "${NGINX_SITE}" ]; then
  skip "nginx site config already present"
else
  cat > "${NGINX_SITE}" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF
  ln -sf "${NGINX_SITE}" "/etc/nginx/sites-enabled/${APP_NAME}"
  rm -f /etc/nginx/sites-enabled/default
fi
nginx -t && systemctl reload nginx

# ----------------------------- 10. firewall --------------------------------
log "Firewall (ufw)"
if have ufw; then
  ufw allow OpenSSH    >/dev/null 2>&1 || true
  ufw allow 'Nginx Full' >/dev/null 2>&1 || true
  ufw --force enable   >/dev/null 2>&1 || true
  skip "ufw rules ensured (SSH + Nginx)"
fi

# ----------------------------- 11. HTTPS via certbot -----------------------
if [ "${ENABLE_SSL}" = "1" ]; then
  log "TLS certificate (Let's Encrypt)"
  if [ -d "/etc/letsencrypt/live/${DOMAIN}" ]; then
    skip "certificate already exists for ${DOMAIN}"
  else
    if ! have certbot; then
      apt-get install -y certbot python3-certbot-nginx
    fi
    # Will only succeed if ${DOMAIN} DNS already points to this server.
    certbot --nginx --non-interactive --agree-tos \
      -m "${CERTBOT_EMAIL}" \
      -d "${DOMAIN}" -d "www.${DOMAIN}" \
      || echo "    certbot failed — ensure DNS A records point here, then re-run."
  fi
else
  skip "SSL disabled (ENABLE_SSL=0)"
fi

# ----------------------------- done ----------------------------------------
log "Deploy complete"
echo "    App:    https://${DOMAIN}  (proxied to 127.0.0.1:${PORT})"
echo "    Logs:   pm2 logs ${APP_NAME}"
echo "    Status: pm2 status"
echo
echo "    If this was the first run, edit ${APP_DIR}/.env (ADMIN_PASSWORD,"
echo "    optional API keys), then: pm2 reload ${APP_NAME} --update-env"
